server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  datasource:
    driver-class-name: "org.hsqldb.jdbc.JDBCDriver"
    url: "jdbc:hsqldb:hsql://localhost/playqd_db"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    propersties:
      hibernate:
        jdbc:
          batch_size: 100

playqd:
  library:
    location: "D:/Music/Post-Rock"
logging:
  level:
    web: DEBUG
