server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  datasource:
    url: "jdbc:hsqldb:mem:playqd_db"
    username: playqd
    password: playqd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.HSQLDialect"

springdoc:
  swagger-ui:
    persistAuthorization: true
    tags-sorter: alpha

playqd:
#  library:
#    location: "path to your music folder"
  security:
    user:
      login: admin
      password: admin
    tokenSecret: "a19a27a5-6da3-481b-ba8d-345a6f206960" # any >= 256 bits secret