server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  datasource:
    driver-class-name: "org.hsqldb.jdbc.JDBCDriver"
    url: "jdbc:hsqldb:hsql://localhost/playqd_db"
    username: sa
    password:
#    initialization-mode: never
#    schema: "classpath:/sql/schema.sql"
  jpa:
    hibernate:
      ddl-auto: create
    propersties:
      hibernate:
        jdbc:
          batch_size: 100

playqd:
  library:
    location: "D:/Music/Downtempo"
logging:
  level:
    web: DEBUG
