server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    propersties:
      hibernate:
        jdbc:
          batch_size: 100
springdoc:
  swagger-ui:
    persistAuthorization: true
    tags-sorter: alpha

logging:
  level:
    web: DEBUG
