server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    propersties:
      hibernate:
        jdbc:
          batch_size: 100

logging:
  level:
    web: DEBUG
