server:
  port: 9585
  servlet:
    context-path: "/playqd"

spring:
  datasource:
    driver-class-name: "org.hsqldb.jdbc.JDBCDriver"
    url: "jdbc:hsqldb:hsql://localhost:9004/playqd_db"
    username: bemonovoid
    password: bemonovoidpwd
  jpa:
    hibernate:
      ddl-auto: update
    propersties:
      hibernate:
        jdbc:
          batch_size: 100

playqd:
  library:
    location: "D:/Music"
logging:
  level:
    web: DEBUG
